set -o vi

# basic prompt on the left
PROMPT='%{$fg[cyan]%}%~% %(?.%{$fg[green]%}.%{$fg[red]%})%B$%b '

export TMOUT=3600
export LSCOLORS=EGxxCxxxxxxjj

# Load ZSH git configuration
if [ -f ~/.zshrc_git ]; then
  . ~/.zshrc_git
fi